#define PIN_SERIAL_COMM Serial

#define PIN_BUILTIN_LED 13

#define PIN_DIGITAL_TEMP_SENSORS 22

#define PIN_IO_BASE 40

#define PIN_SOLAR_PUMP 40
#define PIN_RADIATOR_PUMP 41
#define PIN_GAS_BURNER 42
#define PIN_CIRCULATION_PUMP 43
#define PIN_HEAT_CHANGER_PUMP 44

#define PIN_TEMP_TANK A10
#define PIN_TEMP_BOILER A11
#define PIN_TEMP_OUTSIDE A12
#define PIN_TEMP_SOLAR A13
