// OTHERS
#define CMD_TIME 10
#define CMD_FREE_RAM 11
#define CMD_UPTIME 12

// IO
#define CMD_DISABLE_SIMULATION 39
#define CMD_IO_BASE 40

#define CMD_SOLAR_PUMP 40
#define CMD_RADIATOR_PUMP 41
#define CMD_GAS_BURNER 42
#define CMD_CIRCULATION_PUMP 43
#define CMD_HEAT_CHANGER_PUMP 44

// SENSORS
#define CMD_TEMP_WATER 60
#define CMD_TEMP_HC 61
#define CMD_TEMP_TANK 62
#define CMD_TEMP_SOLAR 63

// CONFIG
#define CMD_CONF_HOLIDAY_MODE 80
#define CMD_CONF_PREHEAT_HOUR_FROM 81
#define CMD_CONF_PREHEAT_TARGET_TEMP_HC 82
#define CMD_CONF_PREHEAT_TARGET_TEMP_WATER 83
#define CMD_CONF_NORMAL_TEMP_HC 84
#define CMD_CONF_NORMAL_TEMP_WATER 85
