#define CONFIG_CONTROLLER 0
#define IO_CONTROLLER 1
#define TEMPERATURE_CONTROLLER 2
#define SOLAR_CONTROLLER 3
#define COMM_CONTROLLER 4
#define HEATER_CONTROLLER 5
#define DISPLAY_CONTROLLER 6
#define BROADCAST_CONTROLLER 7
